services:
  postgresql:
    image:
      postgres:latest
    restart: always
    volumes:
      - ./data/ecommerce-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: localpw


#  prometheus:
#    image: prom/prometheus:v2.7.2
#    restart: always
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - '9090:9090'
#
#
#  pushgateway:
#    image: prom/pushgateway:v0.6.0
#    restart: always
#    ports:
#      - '9091:9091'
#
#  grafana:
#    image: grafana/grafana:6.0.2
#    restart: always
#    ports:
#      - '3000:3000'