spring:
  application:
    name: ecommerce-api
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?profileSQL=true
    username: postgres
    password: localpw
    hikari:
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
logging:
  level:
    root: INFO